# SwiftLint configuration for Delamain projects

disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_collection_literal
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - legacy_multiple
  - modifier_order
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - Package.swift
  - "*/Generated/*"

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3
